#!/usr/bin/env bash

set -euo pipefail

ensure_git() {
    local url=$1
    local dir=$2

    if [[ ! -d $dir ]]; then
        git clone "$url" "$dir"
    else
        git -C "$dir" pull --rebase
    fi
}

ensure_git \
    https://github.com/junegunn/vader.vim \
    ./tests/.vim/pack/default/start/vim-vader

run_vim() {
    vim --not-a-term -N --clean -u ./tests/.vimrc "$@"
}

run_vim '+Vader! tests/{unit,integration}/**.vader'
